name: "Wait"
description: "Wait a designated number of milliseconds"
inputs:
  resource:
    description: "The Canvas Resource"
    required: true
  files:
    description: "Files to be synced"
    required: true
  css:
    description: "The .css files"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
